import aditiYadavImage from "./assets/aditiYadav.jpg";
import chetanAmritanshuImage from "./assets/chetanAmritanshu.jpeg";
import rituBhangaleImage from "./assets/rituBhangale.jpg";
import avaniBahetiImage from "./assets/avaniBaheti.jpg";
import devanshuGuptaImage from "./assets/devanshuGupta.jpg";
import divyanshKumarImage from "./assets/divyanshKumar.jpg";
import mohitKothariImage from "./assets/mohitKothari.jpg";
import mihikaParmarImage from "./assets/mihikaParmar.jpeg";
import omkarKadamImage from "./assets/omkarKadam.jpg";
import manasKapoorImage from "./assets/manasKapoor.jpg";
import piyushAgarwalImage from "./assets/piyushAgarwal.jpg";
import rajatSharmaImage from "./assets/rajatSharma.jpeg";
import satyamShuklaImage from "./assets/satyamShukla.jpg";
import umaImage from "./assets/uma.jpg";
import shivamImage from "./assets/shivam.jpg";
import srishtiPandeyImage from "./assets/srishtiPandey.jpeg";
import tanishaBhargavaImage from "./assets/tanishaBhargava.jpeg";
import uditAgarwalImage from "./assets/uditAgarwal.jpg";
import vishalGoyalImage from "./assets/vishalGoyal.jpg";
import yashMishraImage from "./assets/yashMishra.jpeg";
import yogeshSewadaImage from "./assets/yogeshSewada.jpg";
import nikhilDahriyaImage from "./assets/nikhilDahriya.jpg";
import exampleImage from "./assets/nikhilDahriya.jpg";
import ambujRajImage from "./assets/ambujRaj.jpeg";
import chiragGargImage from "./assets/chiragGarg.jpeg";
import parasSaxenaImage from "./assets/parasSaxena.jpg";
import bhaveshChaudhariImage from "./assets/bhaveshChaudhari.jpeg";

export default [
  {
    id: 1,
    name: "Aditi Yadav",
    image: aditiYadavImage,
    linkedinLink: "https://www.linkedin.com/in/aditiyadav03/",
    instagramLink: "https://www.instagram.com/aditiiyadavv14/",
    githubLink: "https://github.com/aditi1403",
    team: "content",
    email: "aditi03y@gmail.com",
  },
  // {
  //   id: 2,
  //   name: "Tanmayee P. Gosavi",
  //   image: exampleImage,
  //   linkedinLink: "",
  //   instagramLink: "",
  //   githubLink: "",
  //   team: "content",
  // },
  {
    id: 3,
    name: "Chetan Amritanshu",
    image: chetanAmritanshuImage,
    linkedinLink: "#",
    instagramLink: "#",
    githubLink: "#",
    team: "content",
    email: "#",
  },
  {
    id: 4,
    name: "Nikhil Dahriya",
    image: nikhilDahriyaImage,
    linkedinLink: "#",
    instagramLink: "#",
    githubLink: "#",
    team: "content",
    email: "#",
  },
  {
    id: 5,
    name: "Ritu Bhangale",
    image: rituBhangaleImage,
    linkedinLink: "https://www.linkedin.com/in/ritu-bhangale-11baa9201/",
    instagramLink: "https://www.instagram.com/_rits8_/?utm_medium=copy_link",
    githubLink: "https://github.com/Ritu-bhangale",
    team: "designers",
    email: "ritusbhangale@gmail.com",
  },
  {
    id: 6,
    name: "Mohit Kothari",
    image: mohitKothariImage,
    linkedinLink: "#",
    instagramLink: "#",
    githubLink: "#",
    team: "designers",
    email: "#",
  },
  {
    id: 7,
    name: "Shivam",
    image: shivamImage,
    linkedinLink: "https://www.linkedin.com/in/shivam-s-7b8625211/",
    instagramLink: "https://www.instagram.com/shivamss056",
    githubLink: "https://github.com/Shivam25092001",
    team: "designers",
    email: "ss056989@gmail.com",
  },
  // {
  //   id: 8,
  //   name: "Pranesh Ajay Ghadge",
  //   image: exampleImage,
  //   linkedinLink: "",
  //   instagramLink: "",
  //   githubLink: "",
  //   team: "designers",
  // },
  {
    id: 9,
    name: "Bhavesh Chaudhari",
    image: bhaveshChaudhariImage,
    linkedinLink: "https://www.linkedin.com/in/bhavesh-chaudhari-bb4966208/",
    instagramLink: "https://www.instagram.com/bhaveshc0",
    githubLink: "https://github.com/bhavesh-chaudhari",
    team: "developers",
    email: "bhic2030@gmail.com",
  },
  {
    id: 10,
    name: "Ambuj Raj",
    image: ambujRajImage,
    linkedinLink: "https://www.linkedin.com/in/ambuj-raj-542913201",
    instagramLink: "https://www.instagram.com/real_ambuj/",
    githubLink: "https://github.com/ambujraj2001",
    team: "developers",
    email: "bt20cse054@iiitn.ac.in",
  },
  {
    id: 11,
    name: "Tanisha Bhargava",
    image: tanishaBhargavaImage,
    linkedinLink: "https://www.linkedin.com/in/tanisha-bhargava-b33537211/",
    instagramLink: "https://www.instagram.com/tanishabhargava/",
    githubLink: "https://github.com/Tanisha-99",
    team: "developers",
    email: "bt20cse187@iiitn.ac.in",
  },
  {
    id: 12,
    name: "Srishti Pandey",
    image: srishtiPandeyImage,
    linkedinLink: "https://www.linkedin.com/in/srishti-pandey-7a7208211",
    instagramLink: "https://instagram.com/srishti_048?utm_medium=copy_link",
    githubLink: "https://github.com/Srishti-Pandey10",
    team: "developers",
    email: "bt20cse068@iiitn.ac.in",
  },
  {
    id: 13,
    name: "Paras Saxena",
    image: parasSaxenaImage,
    linkedinLink: "https://www.linkedin.com/in/paras-saxena-1b7984202",
    instagramLink: "https://instagram.com/paras_saxena77",
    githubLink: "https://github.com/paras-saxena11",
    team: "developers",
    email: "paras.saxena11@gmail.com",
  },
  {
    id: 14,
    name: "Satyam Shukla",
    image: satyamShuklaImage,
    linkedinLink: "https://www.linkedin.com/in/satyam-shukla-b63043130",
    instagramLink: "https://www.instagram.com/satyam_shukla068/",
    githubLink: "https://github.com/Satyamshukla007901",
    team: "developers",
    email: "bt20cse007@iiitn.ac.in",
  },
  {
    id: 15,
    name: "Udit Agarwal",
    image: uditAgarwalImage,
    linkedinLink: "https://linkedin.com/in/udit-agrawal-986091228",
    instagramLink: "https://www.instagram.com/udit_agrawal43",
    githubLink: "https://github.com/Udit43",
    team: "developers",
    email: "agrawal.udit43@gmail.com",
  },
  {
    id: 16,
    name: "Divyansh Kumar",
    image: divyanshKumarImage,
    linkedinLink:
      "https://www.linkedin.com/in/divyansh-kumar-9a5856192/?originalSubdomain=in",
    instagramLink: "https://instagram.com/drock_2001_",
    githubLink: "https://github.com/Drock2001",
    team: "management",
    email: "#",
  },
  {
    id: 17,
    name: "Mihika Parmar",
    image: mihikaParmarImage,
    linkedinLink: "https://www.linkedin.com/in/mihika-parmar-776711201/",
    instagramLink: "https://www.instagram.com/miheeka.png",
    githubLink: "https://github.com/mihikaparmar",
    team: "management",
    email: "mihikaparmar20@gmail.com",
  },
  {
    id: 18,
    name: "Avani Baheti",
    image: avaniBahetiImage,
    linkedinLink: "https://www.linkedin.com/in/avani-baheti-19651b206",
    instagramLink: "https://www.instagram.com/avani._.maheshwari/",
    githubLink: "https://github.com/AvaniBaheti",
    team: "management",
    email: "avanibaheti7@gmail.com",
  },
  // {
  //   id: 19,
  //   name: "Shrishti Shah",
  //   image: exampleImage,
  //   linkedinLink: "www.linkedin.com/in/shrishti-shah-s18",
  //   instagramLink: "https://www.instagram.com/_shrishti18_/",
  //   githubLink: "https://github.com/Shrishti18",
  //   team: "management",
  //   email: "shrishtishah2002@gmail.com",
  // },
  {
    id: 20,
    name: "Uma",
    image: umaImage,
    linkedinLink: "https://www.linkedin.com/in/uma-l-33b443205",
    instagramLink: "https://www.instagram.com/uma_0195",
    githubLink: "https://github.com/Uma-5-9",
    team: "management",
    email: "umesharanya59@gmail.com",
  },

  // {
  //   id: 21,
  //   name: "Sahil Kothiwala",
  //   image: exampleImage,
  //   linkedinLink: "",
  //   instagramLink: "",
  //   githubLink: "",
  //   team: "video",
  //   email:
  // },
  {
    id: 22,
    name: "Vishal Goyal",
    image: vishalGoyalImage,
    linkedinLink: "https://www.linkedin.com/in/vishal-goyal-00195b1b7",
    instagramLink: "https://www.instagram.com/viishal_goyal",
    githubLink: "https://github.com/goyalvishal03",
    team: "video",
    email: "bt20cse134@iiitn.ac.in",
  },
  {
    id: 23,
    name: "Devanshu Gupta",
    image: devanshuGuptaImage,
    linkedinLink: "https://www.linkedin.com/in/devanshu-gupta-574098202",
    instagramLink: "https://www.instagram.com/dev_gupta236",
    githubLink: "https://github.com/Devanshu236",
    team: "video",
    email: "bt20ece015@iiitn.ac.in",
  },
  {
    id: 24,
    name: "Rajat Sharma",
    image: rajatSharmaImage,
    linkedinLink: "https://www.linkedin.com/in/rajat-sharma-8a7624201/",
    instagramLink: "https://www.instagram.com/jhambura_rajat",
    githubLink: "https://github.com/rjtsharma3538/hbd",
    team: "video",
    email: "rjtsharma3538@gmail.com",
  },
  {
    id: 25,
    name: "Omkar Kadam",
    image: omkarKadamImage,
    linkedinLink: "https://www.linkedin.com/in/omkar-kadam-865374204/",
    instagramLink: "https://instagram.com/_omkar_kadam_",
    githubLink: "https://github.com/kadamomkar",
    team: "video",
    email: "bt20cse173@iiit.ac.in",
  },
  {
    id: 26,
    name: "Yash Mishra",
    image: yashMishraImage,
    linkedinLink: "https://www.linkedin.com/in/yash-mishra-649090216/",
    instagramLink: "https://www.instagram.com/iam__yashmishra/",
    githubLink: "https://github.com/Geekboieyash",
    team: "video",
    email: "#",
  },
  {
    id: 27,
    name: "Manas Kapoor",
    image: manasKapoorImage,
    linkedinLink: "https://www.linkedin.com/in/manas-kapoor-27248b201",
    instagramLink: "https://www.instagram.com/mqnqsk",
    githubLink: "https://github.com/ManasKapoor18",
    team: "developers",
    email: "manasmk2016@gmail.com",
  },
  {
    id: 28,
    name: "Chirag Garg",
    image: chiragGargImage,
    linkedinLink: "https://www.linkedin.com/in/chirag-garg-1606a616b",
    instagramLink: "https://www.instagram.com/chiragarg890/",
    githubLink: "https://github.com/chiraggarg890",
    team: "management",
    email: "bt20cse208@iiitn.ac.in",
  },
  {
    id: 29,
    name: "Chirag Carg",
    image: chiragGargImage,
    linkedinLink: "https://www.linkedin.com/in/chirag-garg-1606a616b",
    instagramLink: "https://www.instagram.com/chiragarg890/",
    githubLink: "https://github.com/chiraggarg890",
    team: "heads",
    email: "bt20cse208@iiitn.ac.in",
  },
  {
    id: 30,
    name: "Ambuj Raj",
    image: ambujRajImage,
    linkedinLink: "https://www.linkedin.com/in/ambuj-raj-542913201",
    instagramLink: "https://www.instagram.com/real_ambuj/",
    githubLink: "https://github.com/ambujraj2001",
    team: "heads",
    email: "bt20cse054@iiitn.ac.in",
  },
];
