import aditiYadavImage from "./assets/aditiYadav.jpg"
import chetanAmritanshuImage from "./assets/chetanAmritanshu.jpeg"
import rituBhangaleImage from "./assets/rituBhangale.jpg";
import avaniBahetiImage from "./assets/avaniBaheti.jpg"
import devanshuGuptaImage from "./assets/devanshuGupta.jpg"
import divyanshKumarImage from "./assets/divyanshKumar.jpg"
import mohitKothariImage from "./assets/mohitKothari.jpg";
import mihikaParmarImage from "./assets/mihikaParmar.jpeg"
import omkarKadamImage from "./assets/omkarKadam.jpg"
import manasKapoorImage from "./assets/manasKapoor.jpg"
import piyushAgarwalImage from "./assets/piyushAgarwal.jpg"
import rajatSharmaImage from "./assets/rajatSharma.jpeg";
import satyamShuklaImage from "./assets/satyamShukla.jpg";
import umaImage from "./assets/uma.jpg";
import shivamImage from "./assets/shivam.jpg";
import srishtiPandeyImage from "./assets/srishtiPandey.jpeg";
import tanishaBhargavaImage from "./assets/tanishaBhargava.jpeg";
import uditAgarwalImage from "./assets/uditAgarwal.jpg";
import vishalGoyalImage from "./assets/vishalGoyal.jpg";
import yashMishraImage from "./assets/yashMishra.jpeg";
import yogeshSewadaImage from "./assets/yogeshSewada.jpg";
import nikhilDahriyaImage from "./assets/nikhilDahriya.jpg";
import exampleImage from "./assets/nikhilDahriya.jpg";

export default [
  {
    id: 1,
    name: "Aditi Yadav",
    image: aditiYadavImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "content",
    email: ""
  },
  {
    id: 2,
    name: "Tanmayee P. Gosavi",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "content",
  },
  {
    id: 3,
    name: "Chetan Amritanshu",
    image: chetanAmritanshuImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "content",
  },
  {
    id: 4,
    name: "Nikhil Dahriya",
    image: nikhilDahriyaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "content",
  },
  {
    id: 5,
    name: "Ritu Bhangale",
    image: rituBhangaleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "designers",
  },
  {
    id: 6,
    name: "Mohit Kothari",
    image: mohitKothariImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "designers",
  },
  {
    id: 7,
    name: "Shivam",
    image: shivamImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "designers",
  },
  {
    id: 8,
    name: "Pranesh Ajay Ghadge",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "designers",
  },
  {
    id: 9,
    name: "Bhavesh Chaudhari",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 10,
    name: "Ambuj Raj",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 11,
    name: "Tanisha Bhargava",
    image: tanishaBhargavaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 12,
    name: "Srishti Pandey",
    image: srishtiPandeyImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 13,
    name: "Paras Saxena",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 14,
    name: "Satyam Shukla",
    image: satyamShuklaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 15,
    name: "Udit Agarwal",
    image: uditAgarwalImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 16,
    name: "Mihika Parmar",
    image: mihikaParmarImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "management",
  },
  {
    id: 17,
    name: "Avani Baheti",
    image: avaniBahetiImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "management",
  },
  {
    id: 18,
    name: "Shrishti Shah",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "management",
  },

  {
    id: 19,
    name: "Uma",
    image: umaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "management",
  },
  {
    id: 20,
    name: "Chirag Garg",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "management",
  },
  {
    id: 21,
    name: "Sahil Kothiwala",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 22,
    name: "Vishal Goyal",
    image: vishalGoyalImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 23,
    name: "Devanshu Gupta",
    image: devanshuGuptaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 24,
    name: "Rajat Sharma",
    image: rajatSharmaImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 25,
    name: "Omkar Kadam",
    image: omkarKadamImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 26,
    name: "Yash Mishra",
    image: yashMishraImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "video",
  },
  {
    id: 27,
    name: "Manas Kapoor",
    image: manasKapoorImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "developers",
  },
  {
    id: 28,
    name: "Divyansh Kumar",
    image: divyanshKumarImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "heads",
  },
  {
    id: 29,
    name: "Chirag Carg",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "heads",
  },
  {
    id: 30,
    name: "Ambuj Raj",
    image: exampleImage,
    linkedinLink: "",
    instagramLink: "",
    githubLink: "",
    team: "heads",
  },
];
